version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"

  app:
    build: .
    depends_on:
      - selenium
    volumes:
      - ./app:/app
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    command: python /app/main.py
